<#
.SYNOPSIS
  Builds FRENCH_REVIEW.md from the shipped French XML, for TRANSLATIONS.md's "Systematic French
  review by Virginie" (2026-09-30).
.DESCRIPTION
  Reads every French DefInjected file of this mod (Mod/Languages/French and the WhaleysDogs
  compatibility folder). Unlike a mod ported from another language, this one carries its English
  source inline: every entry is preceded by an `<!-- EN: ... -->` comment written when the key was
  added, so English is read from that comment rather than resolved against Mod/Defs. Original is
  the same English: this port's source (cucumpear's and lavie2k's Dalmatians) has no non-English
  text of its own (ATTRIBUTION.md), stated once at the top of the generated file rather than on
  every row.

  A row is flagged with a trailing `?` column when its French holds a two-segment
  `{PAWN_gender ? x : y}` switch (the three-segment rule, TRANSLATIONS.md ss3, requires a neutral
  third segment) or an unresolved `???`/`TODO` marker. No row of this mod uses the gender switch at
  all today: every French text here is a noun label or a leather adjective, not a sentence that
  agrees with a pawn, so the flag exists for the day one is added and should stay empty until then.
#>
param(
    [string]$Root = (Split-Path $PSScriptRoot -Parent),
    [string]$OutFile = (Join-Path (Split-Path $PSScriptRoot -Parent) 'FRENCH_REVIEW.md')
)

function Get-EntriesWithEnglish($path) {
    $rows = [ordered]@{}
    if (-not (Test-Path $path)) { return $rows }
    $xml = [xml](Get-Content $path -Raw -Encoding UTF8)
    $pendingEn = $null
    foreach ($node in $xml.LanguageData.ChildNodes) {
        if ($node.NodeType -eq 'Comment') {
            if ($node.InnerText -match '^\s*EN:\s*(.*)$') { $pendingEn = $Matches[1].Trim() }
            continue
        }
        if ($node.NodeType -ne 'Element') { continue }
        $rows[$node.Name] = [pscustomobject]@{ French = $node.InnerText; English = $pendingEn }
        $pendingEn = $null
    }
    return $rows
}

$frenchFiles = @(
    Join-Path $Root 'Mod/Languages/French'
    Join-Path $Root 'Mod/Compatibility/WhaleysDogs/Languages/French'
) | Where-Object { Test-Path $_ } | ForEach-Object { Get-ChildItem $_ -Recurse -Filter *.xml } | Sort-Object FullName

$out = New-Object System.Text.StringBuilder
[void]$out.AppendLine("# French review")
[void]$out.AppendLine()
[void]$out.AppendLine("Generated by `` _tools/Generate-FrenchReview.ps1`` for TRANSLATIONS.md's systematic French review.")
[void]$out.AppendLine("**Original column: same as English throughout.** This port's source, cucumpear's and lavie2k's")
[void]$out.AppendLine("Dalmatians, has no text in another language (ATTRIBUTION.md): it was written in English, and")
[void]$out.AppendLine("English is what this repository carries as every entry's own `` <!-- EN: ... --> `` comment,")
[void]$out.AppendLine("read from there rather than resolved against `` Mod/Defs``, since that comment is this repository's")
[void]$out.AppendLine("own record of the source text at the time the French was written.")
[void]$out.AppendLine()
[void]$out.AppendLine("Generated $(Get-Date -Format 'yyyy-MM-dd'), revision: $(git -C $Root rev-parse --short HEAD) (tree clean when generated), gender-agreement rule of 2026-09-30.")
[void]$out.AppendLine()

$totalRows = 0
$flagged = 0
foreach ($ff in $frenchFiles) {
    $rel = $ff.FullName.Substring($Root.Length + 1) -replace '\\', '/'
    $entries = Get-EntriesWithEnglish $ff.FullName
    if ($entries.Count -eq 0) { continue }

    [void]$out.AppendLine("## $rel")
    [void]$out.AppendLine()
    [void]$out.AppendLine("| Key or path | Original | English | French |")
    [void]$out.AppendLine("|---|---|---|---|")
    foreach ($key in $entries.Keys) {
        $row = $entries[$key]
        $fr = $row.French
        # A tool label carries its English in its own id (tools.left_claw.label -> left claw): derived, not guessed.
        $en = '*(no EN: comment above this key -- check by hand)*'
        if ($row.English) { $en = $row.English }
        elseif ($key -match '\.tools\.([A-Za-z0-9]+(?:_[A-Za-z0-9]+)*)\.label$') { $en = ($Matches[1] -replace '_', ' ') + ' *(derived from the id)*' }
        $orig = $en
        $isTwoSegmentSwitch = ($fr -match '\{[A-Za-z_]+_gender\s*\?') -and ($fr -notmatch '\{[A-Za-z_]+_gender\s*\?[^:{}]*:[^:{}]*:[^:{}]*\}')
        $flag = if ($isTwoSegmentSwitch -or $fr -match '\?\?\?|TODO') { $script:flagged++; ' | ?' } else { '' }
        $script:totalRows++
        $origCell = ($orig -replace '\|', '\|') -replace "`n", ' '
        $enCell = ($en -replace '\|', '\|') -replace "`n", ' '
        $frCell = ($fr -replace '\|', '\|') -replace "`n", ' '
        $keyCell = $key -replace '\|', '\|'
        [void]$out.AppendLine("| $keyCell | $origCell | $enCell | $frCell$flag |")
    }
    [void]$out.AppendLine()
}

[System.IO.File]::WriteAllText($OutFile, $out.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Output "wrote $OutFile ($totalRows rows, $flagged flagged)"
